services:
  webhook-service:
    build: 
      context: .
    container_name: bitrix-sentry-webhook-service
    ports:
      - "8008:8000"
    env_file:
      - .env.test

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: webhook-tests
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: ["pytest", "-v", "tests"]
    env_file:
      - .env.test