FROM python:3.10.17-slim

ENV PYTHONPATH=/workspace

WORKDIR /app

COPY requirements.txt requirements-test.txt ./
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir -r requirements-test.txt

COPY app/ ./app/
COPY tests/ ./tests/

CMD ["pytest", "-v", "/tests"]